version: '3'

services:
  mysql-development:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: hu2023
      MYSQL_DATABASE: bira-app
    ports:
      - "3308:3306"
  
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"